#!/bin/bash

echo "=== Quick MNIST Test ==="
echo "Run this command:"
echo ""
echo "sbcl"
echo ""
echo "Then paste these commands one by one:"
echo ""
echo "(load \"packages.lisp\")"
echo "(load \"src/data-loader.lisp\")"
echo "(load \"src/neural-net.lisp\")"
echo "(load \"src/training.lisp\")"
echo "(load \"src/inference.lisp\")"
echo ""
echo ";; Load test data"
echo "(multiple-value-bind (train-images train-labels test-images test-labels)"
echo "    (mnist-ocr::load-mnist-data \"data/\")"
echo "  (format t \"Loaded ~D test images~%\" (length test-images))"
echo ""
echo "  ;; Create network"
echo "  (defparameter *net* (mnist-ocr::create-network 784 128 10))"
echo "  (format t \"Network created~%\")"
echo ""
echo "  ;; Test prediction"
echo "  (let* ((image (aref test-images 0))"
echo "         (actual (aref test-labels 0)))"
echo "    (format t \"Testing image with label ~A~%\" actual)"
echo "    (handler-case"
echo "        (let ((pred (mnist-ocr::predict-digit *net* image)))"
echo "          (format t \"SUCCESS: Predicted ~A~%\" pred))"
echo "      (error (e) (format t \"ERROR: ~A~%\" e)))))"
echo ""
echo "To exit SBCL: (quit)"